# Generated by Django 4.1.13 on 2025-09-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
        ('olevel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oleveldataset',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='o_level_uploads', to='configurations.educationlevel'),
            preserve_default=False,
        ),
    ]
