# Generated by Django 4.1.13 on 2025-09-09 09:47

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0002_primaryupload_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(max_length=100)),
                ('classes', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('predictions_csv', models.FileField(blank=True, null=True, upload_to='predictions/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('primary', 'Primary'), ('olevel', 'O-Level'), ('alevel', 'A-Level')], default='primary', max_length=20)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_in_file', models.PositiveIntegerField()),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(max_length=255)),
                ('proba', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='primary.predictionbatch')),
            ],
        ),
        migrations.AddField(
            model_name='predictionbatch',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='primary.uploadeddataset'),
        ),
    ]
