# Generated by Django 4.1.13 on 2025-09-01 17:43

import artifacts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('task', models.CharField(choices=[('classification', 'Classification'), ('forecasting', 'Forecasting')], max_length=20)),
                ('model_format', models.CharField(choices=[('sklearn', 'scikit-learn/joblib/pickle'), ('keras', 'Keras/TensorFlow (.h5 or SavedModel)'), ('statsmodels', 'statsmodels/pmdarima'), ('xgboost', 'XGBoost'), ('lightgbm', 'LightGBM'), ('onnx', 'ONNX (optional)')], default='sklearn', max_length=20)),
                ('file', models.FileField(upload_to=artifacts.models.model_upload_path)),
                ('feature_list', models.JSONField(blank=True, help_text='Optional: list of feature names expected by the model.', null=True)),
                ('target_name', models.CharField(blank=True, help_text='Optional: target column name (for docs).', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='configurations.educationlevel')),
            ],
        ),
        migrations.CreateModel(
            name='InferenceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_label', models.CharField(max_length=200)),
                ('dataset_path', models.TextField()),
                ('params', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(auto_now=True)),
                ('ok', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('output_csv', models.FileField(blank=True, null=True, upload_to=artifacts.models.inference_output_path)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='artifacts.modelartifact')),
            ],
        ),
    ]
