# Generated by Django 4.1.13 on 2025-08-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='datasets/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='processed/')),
                ('n_rows', models.IntegerField(default=0)),
                ('n_cols', models.IntegerField(default=0)),
            ],
        ),
    ]
