# Generated by Django 4.1.13 on 2025-09-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
        ('alevel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALevelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='a_level_uploads', to='configurations.educationlevel')),
            ],
        ),
    ]
